server:
  port: 9990




spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://db-mysql:3307/community?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
